# 异常处理

# 异常的分类

所有异常类都是`Throwable`​的子类

分支一：`Error`​：Java运行时的内部错误，通常用来指明与运行环境相关的错误。应用程序不应该抛出这类异常，它们在Java程序处理的范畴之外。

分支二：`Exception`​：用于程序中应该捕获的异常，有两个分支`IOException`​、`RuntimeException`​。

​**​`RuntimeException`​**​:子类：`IndexOutOfBoundsException`​，某排序索引超出范围时抛出的异常；`ArithmeticException`​，异常的运算条件，例如`11/0`​

## Java 内置异常类

Java 语言定义了一些异常类在 java.lang 标准包中。

标准运行时异常类的子类是最常见的异常类。由于 java.lang 包是默认加载到所有的 Java 程序的，所以大部分从运行时异常类继承而来的异常都可以直接使用。

Java 根据各个类库也定义了一些其他的异常，下面的表中列出了 Java 的非检查性异常。

|**异常**|**描述**|
| ---------------------------------| ----------------------------------------------------------------------------------------------------------------------|
|ArithmeticException|当出现异常的运算条件时，抛出此异常。例如，一个整数"除以零"时，抛出此类的一个实例。|
|ArrayIndexOutOfBoundsException|用非法索引访问数组时抛出的异常。如果索引为负或大于等于数组大小，则该索引为非法索引。|
|ArrayStoreException|试图将错误类型的对象存储到一个对象数组时抛出的异常。|
|ClassCastException|当试图将对象强制转换为不是实例的子类时，抛出该异常。|
|IllegalArgumentException|抛出的异常表明向方法传递了一个不合法或不正确的参数。|
|IllegalMonitorStateException|抛出的异常表明某一线程已经试图等待对象的监视器，或者试图通知其他正在等待对象的监视器而本身没有指定监视器的线程。|
|IllegalStateException|在非法或不适当的时间调用方法时产生的信号。换句话说，即 Java 环境或 Java 应用程序没有处于请求操作所要求的适当状态下。|
|IllegalThreadStateException|线程没有处于请求操作所要求的适当状态时抛出的异常。|
|IndexOutOfBoundsException|指示某排序索引（例如对数组、字符串或向量的排序）超出范围时抛出。|
|NegativeArraySizeException|如果应用程序试图创建大小为负的数组，则抛出该异常。|
|NullPointerException|当应用程序试图在需要对象的地方使用 `null`​ 时，抛出该异常|
|NumberFormatException|当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出该异常。|
|SecurityException|由安全管理器抛出的异常，指示存在安全侵犯。|
|StringIndexOutOfBoundsException|此异常由 `String`​ 方法抛出，指示索引或者为负，或者超出字符串的大小。|
|UnsupportedOperationException|当不支持请求的操作时，抛出该异常。|

下面的表中列出了 Java 定义在 java.lang 包中的检查性异常类。

|**异常**|**描述**|
| ----------------------------| ----------------------------------------------------------------------------------------------------------------------|
|ClassNotFoundException|应用程序试图加载类时，找不到相应的类，抛出该异常。|
|CloneNotSupportedException|当调用 `Object`​ 类中的 `clone`​ 方法克隆对象，但该对象的类无法实现 `Cloneable`​ 接口时，抛出该异常。|
|IllegalAccessException|拒绝访问一个类的时候，抛出该异常。|
|InstantiationException|当试图使用 `Class`​ 类中的 `newInstance`​ 方法创建一个类的实例，而指定的类对象因为是一个接口或是一个抽象类而无法实例化时，抛出该异常。|
|InterruptedException|一个线程被另一个线程中断，抛出该异常。|
|NoSuchFieldException|请求的变量不存在|
|NoSuchMethodException|请求的方法不存在|

# 异常的使用

## 异常捕获

通常使用`try-catch`​ 块来捕获并处理异常

```java
try{
	//可能出现的异常代码
}catch
{
	//对异常1的处理
}
catch
{
	//对异常2的处理
}
```

```java
try{
        array1[3]=5;
    }catch(NullPointerException e){
        System.out.println("空指针异常");
    }
```

如果保护代码中发生异常，异常被抛给第一个 catch 块。

如果抛出异常的数据类型与 ExceptionType1 匹配，它在这里就会被捕获。

如果不匹配，它会被传递给第二个 catch 块。

如此，直到异常被捕获或者通过所有的 catch 块。

注意，如果有多个catch语句，捕获父类的catch语句必须放在后面，否则它会捕获它的所有子类异常。

## printStackTrace()方法：获取异常的堆栈信息

​`printStackTrace()`​ 方法可以帮助开发者了解异常发生的位置和调用栈信息

例如：`at PrintStackTraceExample.main(PrintStackTraceExample.java:6)`​ 表示异常是在 `main`​ 方法的第 6 行抛出的，而 `at PrintStackTraceExample.divide(PrintStackTraceExample.java:14)`​ 表示异常的根源是在 `divide`​ 方法的第 14 行。

## finally语句块

finally 关键字用来创建在 try 代码块后面执行的代码块。无论是否发生异常，finally 代码块中的代码总会被执行。在 finally 代码块中，可以运行清理类型等收尾善后性质的语句。

finally 代码块出现在 catch 代码块最后。

```java
try{
  // 程序代码
}catch(异常类型1 异常的变量名1){
  // 程序代码
}catch(异常类型2 异常的变量名2){
  // 程序代码
}finally{
  // 程序代码
}
```

## 方法抛出异常

### `throws`​

```java
修饰符 返回值类型 方法名() throws 异常类型1，异常类型2{
	//方法体
}
```

### `throw`​

throw 关键字用于在当前方法中抛出一个异常。

通常情况下，当代码执行到某个条件下无法继续正常执行时，可以使用 throw 关键字抛出异常，以告知调用者当前代码的执行状态。

例如，下面的代码中，在方法中判断 num 是否小于 0，如果是，则抛出一个 IllegalArgumentException 异常。

```java
public void checkNumber(int num) {
  if (num < 0) {
    throw new IllegalArgumentException("Number must be positive");
  }
}
```

### try-with-resources

JDK7 之后，Java 新增的 try-with-resource 语法结构，旨在自动管理资源，确保资源在使用后能够及时关闭，避免资源泄露 。

try-with-resources 是一种异常处理机制，它能够自动关闭在 try 块中声明的资源，无需显式地在 finally 块中关闭。

在 try-with-resources 语句中，你只需要在 try 关键字后面声明资源，然后跟随一个代码块。无论代码块中的操作是否成功，资源都会在 try 代码块执行完毕后自动关闭。。

```java
try (resource declaration) {
  // 使用的资源
} catch (ExceptionType e1) {
  // 异常块
}
```

### 自定义异常

#### 创建自己的异常类

在 Java 中你可以自定义异常。编写自己的异常类时需要记住下面的几点。

* 所有异常都必须是 Throwable 的子类。
* 如果希望写一个检查性异常类，则需要继承 Exception 类。
* 如果你想写一个运行时异常类，那么需要继承 RuntimeException 类。

```java
class 类名 extends Exception{

}
```

Exception没有定义任何方法，从Throwable继承了一些方法，所以创建自定义的异常类时可以继承Throwable中的方法，也可以重写这些方法。

实例

```java
class IllegalException extends Exception {
    IllegalException(String s) {
        super(s);//调用父类方法
    }
    IllegalException(){

    }
}
public class test {
    public static void main(String[] args) {
        try{
            String level=null;
            level=scoreLevel(90);
            System.out.println("level of 90:"+level);
            level=scoreLevel(120);
            System.out.println("level of 120:"+level);
        }
        catch(IllegalException e){
            e.printStackTrace();
        }
    }
    static String scoreLevel(int i) throws IllegalException
    {
        if(i>=85&&i<=100)
            return "A";
        if (i>=0&&i<85)
            return "B";
        else
            throw new IllegalException("分数不合法");
    }
}
```

运行结果：

level of 90:A  
IllegalException: 分数不合法  
	at test.scoreLevel(test.java:32)  
	at test.main(test.java:17)
